export const APP_CONSTANTS = {
  BCRYPT_ROUNDS: 12,
  JWT_EXPIRES_IN: '15m',
  JWT_REFRESH_EXPIRES_IN: '7d',
  MAX_LOGIN_ATTEMPTS: 5,
  ACCOUNT_LOCK_DURATION: 30 * 60 * 1000,
  PASSWORD_RESET_EXPIRY: 15 * 60 * 1000,
  RATE_LIMIT_TTL: 60 * 1000,
  RATE_LIMIT_MAX: 100,
  MAX_FILE_SIZE: 10 * 1024 * 1024,
  ALLOWED_FILE_TYPES: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf'],
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  CACHE_TTL: 5 * 60,
  CACHE_MAX_ITEMS: 100,
  DB_CONNECTION_TIMEOUT: 30000,
  DB_QUERY_TIMEOUT: 10000,
  API_VERSION: 'v1',
  API_PREFIX: 'api',
  EMAIL_QUEUE_DELAY: 1000,
  SMS_QUEUE_DELAY: 2000,
  SESSION_EXPIRY: 7 * 24 * 60 * 60 * 1000,
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  MIN_NAME_LENGTH: 2,
  MAX_NAME_LENGTH: 50,
  DEFAULT_APPOINTMENT_DURATION: 30,
  MAX_APPOINTMENTS_PER_DAY: 20,
  VITAL_RETENTION_DAYS: 365,
} as const;

export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: 'Invalid email or password',
  ACCOUNT_LOCKED: 'Account is locked due to multiple failed login attempts',
  ACCOUNT_DISABLED: 'Account is disabled',
  TOKEN_EXPIRED: 'Token has expired',
  INVALID_TOKEN: 'Invalid token',
  INSUFFICIENT_PERMISSIONS: 'Insufficient permissions to access this resource',
  ROLE_NOT_AUTHORIZED: 'Your role is not authorized for this action',
  REQUIRED_FIELD: 'This field is required',
  INVALID_EMAIL: 'Please provide a valid email address',
  WEAK_PASSWORD: 'Password does not meet security requirements',
  PASSWORD_MISMATCH: 'Passwords do not match',
  RECORD_NOT_FOUND: 'Record not found',
  DUPLICATE_ENTRY: 'A record with this information already exists',
  FOREIGN_KEY_CONSTRAINT: 'Cannot delete record due to existing references',
  FILE_TOO_LARGE: 'File size exceeds maximum allowed limit',
  INVALID_FILE_TYPE: 'File type is not supported',
  APPOINTMENT_CONFLICT: 'Appointment time conflicts with existing appointment',
  DOCTOR_NOT_AVAILABLE: 'Doctor is not available at the requested time',
  PATIENT_NOT_ASSIGNED: 'Patient is not assigned to this doctor',
} as const;

export const SUCCESS_MESSAGES = {
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  REGISTRATION_SUCCESS: 'Registration successful',
  PASSWORD_CHANGED: 'Password changed successfully',
  PASSWORD_RESET: 'Password reset successfully',
  CREATED_SUCCESS: 'Record created successfully',
  UPDATED_SUCCESS: 'Record updated successfully',
  DELETED_SUCCESS: 'Record deleted successfully',
  APPOINTMENT_SCHEDULED: 'Appointment scheduled successfully',
  APPOINTMENT_CANCELLED: 'Appointment cancelled successfully',
  APPOINTMENT_COMPLETED: 'Appointment completed successfully',
  EMAIL_SENT: 'Email sent successfully',
  SMS_SENT: 'SMS sent successfully',
  NOTIFICATION_SENT: 'Notification sent successfully',
} as const;