export enum VitalType {
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
  HEART_RATE = 'HEART_RATE',
  TEMPERATURE = 'TEMPERATURE',
  OXYGEN_SATURATION = 'OXYGEN_SATURATION',
  BLOOD_SUGAR = 'BLOOD_SUGAR',
  WEIGHT = 'WEIGHT',
  HEIGHT = 'HEIGHT',
}